// @vitest-environment node
import { afterEach, beforeEach, expect, it, vi } from 'vitest'
const mock = vi.hoisted(() => ({ get: vi.fn(), load: vi.fn(), record: vi.fn() }))
vi.mock('@/src/db', () => ({ biometricsDb: {} }))
vi.mock('@/src/lib/dataPathCollect', () => ({ getDataPath: mock.get }))
vi.mock('@/src/lib/healthHistory', () => ({ loadOpenRuns: mock.load, recordSample: mock.record, SAMPLE_INTERVAL_MS: 60000 }))
import { startHealthSampler, stopHealthSampler } from '../healthSampler'
beforeEach(() => {
  vi.useFakeTimers()
  vi.clearAllMocks()
  mock.get.mockResolvedValue({ nodes: [{ id: 'dac', status: 'ok', detail: 'Connected' }] })
  mock.load.mockReturnValue(new Map())
})
afterEach(() => {
  stopHealthSampler()
  vi.useRealTimers()
  vi.restoreAllMocks()
})
it('waits for startup, starts only once, reuses open runs and stops polling', async () => {
  startHealthSampler(1000)
  startHealthSampler(1000)
  expect(mock.get).not.toHaveBeenCalled()
  await vi.advanceTimersByTimeAsync(1000)
  expect(mock.record).toHaveBeenCalledWith({}, expect.any(Map), [{ id: 'dac', status: 'ok', detail: 'Connected' }], expect.any(Number))
  await vi.advanceTimersByTimeAsync(60000)
  expect(mock.load).toHaveBeenCalledOnce()
  expect(mock.record).toHaveBeenCalledTimes(2)
  stopHealthSampler()
  await vi.advanceTimersByTimeAsync(60000)
  expect(mock.record).toHaveBeenCalledTimes(2)
  startHealthSampler(1)
  await vi.advanceTimersByTimeAsync(1)
  expect(mock.load).toHaveBeenCalledTimes(2)
})
it('logs a failed sample and retries next minute', async () => {
  const warn = vi.spyOn(console, 'warn').mockImplementation(() => {})
  mock.get.mockRejectedValueOnce(new Error('Offline')).mockRejectedValueOnce('Not ready')
  startHealthSampler(1)
  await vi.advanceTimersByTimeAsync(60001)
  expect(warn).toHaveBeenCalledWith('[health] sample failed:', 'Offline')
  expect(warn).toHaveBeenCalledWith('[health] sample failed:', 'Not ready')
  await vi.advanceTimersByTimeAsync(60000)
  expect(mock.record).toHaveBeenCalledOnce()
})
