compressionLevel: mixed

enableGlobalCache: false

# Yarn uses PnP by default, but we use the `node-modules` linker for
# compatibility with tools that expect a traditional `node_modules` folder.
enableScripts: false

enableTelemetry: false

logFilters:
  - code: YN0004
    level: discard

# Maintains compatibility and avoids PnP 'spawn sh' errors
nodeLinker: node-modules

# Speeds up the 'Link step' by reducing deep dependency nesting
nmHoistingLimit: dependencies

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-allow-scripts.cjs
    spec: "https://raw.githubusercontent.com/LavaMoat/LavaMoat/main/packages/yarn-plugin-allow-scripts/bundles/@yarnpkg/plugin-allow-scripts.js"

# Configure the NPM minimal age gate to 3 days, meaning packages must be at
# least 3 days old to be installed.
npmMinimalAgeGate: 4320 # 3 days (in minutes)

# Override the minimal age gate, allowing certain packages to be installed
# regardless of their publish age.
npmPreapprovedPackages: []