import { act, fireEvent, render, screen } from '@testing-library/react'
import { afterEach, beforeEach, expect, it, vi } from 'vitest'
import { AICurveWizard } from '../AICurveWizard'
import { loadTemplates, saveTemplate } from '@/src/lib/sleepCurve/curvePrompt'
vi.mock('@/src/hooks/useTemperatureUnit', () => ({ useTemperatureUnit: () => ({ unit: 'F' }) }))
const curve = { name: 'Cool night', bedtime: '22:00', wake: '07:00', points: { '22:00': 78, '02:00': 72, '07:00': 80 }, reasoning: 'Cool overnight, warm before waking.' }
beforeEach(() => {
  localStorage.clear()
  vi.useFakeTimers()
})
afterEach(() => {
  vi.useRealTimers()
  vi.restoreAllMocks()
})
it('imports, edits, saves and applies a curve without writing the schedule directly', async () => {
  const onApply = vi.fn(), onClose = vi.fn()
  Object.defineProperty(navigator, 'clipboard', { configurable: true, value: { readText: vi.fn().mockResolvedValue(JSON.stringify(curve)) } })
  const { rerender } = render(<AICurveWizard open onApply={onApply} onClose={onClose} />)
  fireEvent.click(screen.getByRole('button', { name: 'Import' }))
  fireEvent.change(screen.getByLabelText('AI response JSON'), { target: { value: 'invalid' } })
  act(() => vi.advanceTimersByTime(500))
  expect(screen.getByRole('button', { name: 'Next' }).hasAttribute('disabled')).toBe(true)
  await act(async () => fireEvent.click(screen.getByRole('button', { name: 'Paste from clipboard' })))
  act(() => vi.advanceTimersByTime(500))
  fireEvent.click(screen.getByRole('button', { name: 'Next' }))
  expect(screen.getByText(curve.reasoning)).toBeTruthy()
  fireEvent.click(screen.getByRole('button', { name: 'Add' }))
  fireEvent.change(screen.getByLabelText('Set point 1 time'), { target: { value: '01:00' } })
  fireEvent.click(screen.getByRole('button', { name: 'Increase set point 1 temperature' }))
  fireEvent.click(screen.getByRole('button', { name: 'Remove set point 4' }))
  expect(screen.getByRole('button', { name: 'Remove set point 1' }).hasAttribute('disabled')).toBe(true)
  fireEvent.click(screen.getByRole('button', { name: 'Save template' }))
  expect(loadTemplates()[0].name).toBe(curve.name)
  expect(onApply).not.toHaveBeenCalled()
  fireEvent.click(screen.getByRole('button', { name: 'Use curve' }))
  expect(onApply).toHaveBeenCalledWith({ bedtime: '22:00', wakeTime: '07:00', setPoints: expect.arrayContaining([{ time: '01:00', temperature: 73 }]) })
  expect(onClose).toHaveBeenCalledOnce()
  rerender(<AICurveWizard open={false} onApply={onApply} onClose={onClose} />)
  rerender(<AICurveWizard open onApply={onApply} onClose={onClose} />)
  expect(screen.getByLabelText('Sleep preferences')).toBeTruthy()
})
it('generates and copies a prompt and navigates previously visited steps', async () => {
  const writeText = vi.fn().mockResolvedValue(undefined), share = vi.fn().mockResolvedValue(undefined)
  Object.defineProperty(navigator, 'clipboard', { configurable: true, value: { writeText } })
  Object.defineProperty(navigator, 'share', { configurable: true, value: share })
  render(<AICurveWizard open onApply={vi.fn()} onClose={vi.fn()} />)
  fireEvent.change(screen.getByLabelText('Sleep preferences'), { target: { value: 'Cool until morning' } })
  fireEvent.click(screen.getByRole('button', { name: 'Generate' }))
  await act(async () => fireEvent.click(screen.getByRole('button', { name: /Copy/ })))
  expect(writeText).toHaveBeenCalledWith(expect.stringContaining('Cool until morning'))
  await act(async () => fireEvent.click(screen.getByRole('button', { name: /Share/ })))
  expect(share).toHaveBeenCalledWith({ text: expect.stringContaining('Cool until morning') })
  act(() => vi.advanceTimersByTime(2000))
  fireEvent.click(screen.getByRole('button', { name: 'Next' }))
  fireEvent.click(screen.getByRole('button', { name: 'Back' }))
  fireEvent.click(screen.getByRole('button', { name: '1. Describe' }))
  expect(screen.getByLabelText('Sleep preferences')).toBeTruthy()
})
it('loads and deletes saved templates', () => {
  saveTemplate(curve)
  render(<AICurveWizard open onApply={vi.fn()} onClose={vi.fn()} />)
  fireEvent.click(screen.getByRole('button', { name: /Cool night.*22:00/ }))
  expect(screen.getByRole('button', { name: 'Use curve' })).toBeTruthy()
  fireEvent.click(screen.getByRole('button', { name: '1. Describe' }))
  fireEvent.click(screen.getByRole('button', { name: 'Delete Cool night' }))
  expect(loadTemplates()).toEqual([])
})
