import { LinguiClientProvider } from '@/src/components/providers/LinguiClientProvider'
import { allMessages, getI18nInstance } from '@/src/lib/i18n/appRouterI18n'
import { initLingui, PageLangParam } from '@/src/lib/i18n/initLingui'
import { t } from '@lingui/core/macro'
import linguiConfig from 'lingui.config'
import type { Metadata } from 'next'

export const generateStaticParams = async () => {
  return linguiConfig.locales.map((lang: string) => ({ lang }))
}

export const generateMetadata = async (
  props: PageLangParam,
): Promise<Metadata> => {
  const i18n = getI18nInstance((await props.params).lang)

  return {
    title: t(i18n)`Create Next App`,
    description: t(i18n)`Generated by create next app`,
  }
}

export default async function RootLayout({
  children,
  params,
}: Readonly<{
  children: React.ReactNode
  params: Promise<{ lang: string }>
}>) {
  const { lang } = await params
  initLingui(lang)

  return (
    <LinguiClientProvider
      initialLocale={lang}
      initialMessages={allMessages[lang]}
    >
      {children}
    </LinguiClientProvider>
  )
};
